 create table comments (
        id bigint generated by default as identity,
        client_id bigint,
        comment varchar(255) NOT NULL,
        photo varchar(255),
        username varchar(255) NOT NULL,
        primary key (id)
    )